//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorPageResources", typeof(ErrorPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for cannot be reached!.
        /// </summary>
        public static string body_403 {
            get {
                return ResourceManager.GetString("body_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This fine gentleman could not find the page you were looking for and he looks pretty competent. Maybe it does not exist?.
        /// </summary>
        public static string body_404 {
            get {
                return ResourceManager.GetString("body_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of our server powering hamsters has gone to the farm. Please be patient we find a replacement.
        /// </summary>
        public static string body_500 {
            get {
                return ResourceManager.GetString("body_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our castle is broken!.
        /// </summary>
        public static string body_505 {
            get {
                return ResourceManager.GetString("body_505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 403.
        /// </summary>
        public static string head_403 {
            get {
                return ResourceManager.GetString("head_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 500.
        /// </summary>
        public static string head_500 {
            get {
                return ResourceManager.GetString("head_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 505.
        /// </summary>
        public static string head_505 {
            get {
                return ResourceManager.GetString("head_505", resourceCulture);
            }
        }
    }
}
